version: 2

python:
   version: 3.7
   install:      
      - method: pip
        path: pip install random-profile
        extra_requirements:
            - docs
      - method: setuptools
        path: random_profile
   system_packages: true
