version: 2

python:
   version: 3.7
   install:
      - requirements: requirements.txt
      - method: pip
        path: .
        extra_requirements:
            - docs
      - method: setuptools
        path: random_profile
   system_packages: true
